version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456789
      - MONGO_INITDB_DATABASE=demo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongo-network
    command: ["mongod", "--auth"]

  redis:
    image: redis:latest
    container_name: redis-container-demo
    ports:
      - "6379:6379"
    networks:
      - mongo-network

volumes:
  mongodb-data:
    driver: local

networks:
  mongo-network:
    driver: bridge
